trigger:
  branches:
    include:
    - personal/yankhuan/converter-vsc-extension
    - main
  tags:
    include:
    - v*

jobs:
- job: FHIR_Converter_CI_Tests
  displayName: FHIR-Converter CI Tests

  strategy:
    matrix:
      windows:
        imageName: 'windows-2019'

  pool:
    vmImage: $(imageName)

  variables:
    basicPath: $(Build.SourcesDirectory)/FHIR-Converter

  steps:
  - template: ./fhir-converter-pipeline.yml
