trigger:
  branches:
    include:
    - main

stages: 
- stage: FhirConverter
  jobs:
  - job: Build
    displayName: FHIR Converter Build -

    strategy:
      matrix:
        Windows:
          imageName: 'windows-latest'
        MacOS:
          imageName: "macos-latest"
      maxParallel: 2

    pool:
      vmImage: $(imageName)

    variables:
      basicPath: $(Build.SourcesDirectory)/FHIR-Converter

    steps:
    - template: ./fhir-converter-pipeline.yml
